from __future__ import annotations


_TOKENS = """
:root{--system-blue:#0A84FF;--vision-purple:#7B61FF;--primary:#163A5F;--text:#202124;--muted:#666B73;--weak:#8A9099;--border:rgba(90,102,118,.18);--hairline:rgba(90,102,118,.12);--soft:rgba(245,247,249,.78);--table:rgba(248,249,250,.82);--negative:#A04A4A;--positive:#557A67;--font:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}
*{box-sizing:border-box}html{min-height:100%;background:#EEF3F8}
body{min-height:100%;margin:0;color:var(--text);font-family:var(--font);font-size:15.5px;line-height:1.8;font-variant-numeric:tabular-nums;background:radial-gradient(circle at 12% 5%,rgba(10,132,255,.13),transparent 30%),radial-gradient(circle at 88% 12%,rgba(123,97,255,.11),transparent 28%),linear-gradient(180deg,#F5F8FC 0%,#EDF2F7 100%);background-attachment:fixed}
a{color:#315F86;text-decoration:none}p{margin:10px 0}strong{font-weight:650}code{font-family:var(--font)}
.eyebrow,.chart-kicker{color:var(--system-blue);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}
.chart-component{position:relative;margin:22px 0 30px;padding:20px 22px 18px;border:1px solid rgba(255,255,255,.72);border-radius:18px;background:linear-gradient(145deg,rgba(255,255,255,.88),rgba(247,250,253,.72));box-shadow:0 16px 42px rgba(37,55,76,.09),inset 0 1px 0 rgba(255,255,255,.9);backdrop-filter:blur(22px) saturate(135%);-webkit-backdrop-filter:blur(22px) saturate(135%);overflow:hidden}
.chart-component:before{content:"";position:absolute;inset:0 0 auto;height:2px;background:linear-gradient(90deg,var(--system-blue),var(--vision-purple));opacity:.72}
.chart-header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:8px}.chart-header h2,.chart-header h4{margin:0;color:var(--text);font-size:15px;font-weight:680;line-height:1.5}.chart-kicker{margin:0 0 2px}.chart-unit{color:var(--weak);font-size:11px;white-space:nowrap}
.chart-legend{display:flex;flex-wrap:wrap;gap:7px 18px;margin:10px 0;color:var(--muted);font-size:12px}.chart-legend span{display:inline-flex;align-items:center;gap:7px}.chart-legend i{width:15px;height:3px;border-radius:2px;background:var(--primary)}
.chart-stage{position:relative;margin-top:8px;border-top:1px solid var(--hairline);border-bottom:1px solid var(--hairline);background:rgba(255,255,255,.42)}.chart-component canvas,.chart-card canvas{display:block;width:100%;height:360px;background:transparent}
.chart-tooltip{position:absolute;z-index:4;max-width:320px;padding:7px 10px;border:1px solid rgba(255,255,255,.22);border-radius:9px;background:rgba(24,28,36,.88);box-shadow:0 10px 30px rgba(0,0,0,.18);backdrop-filter:blur(14px);color:#fff;font-size:12px;pointer-events:none}
.chart-explanation,.chart-source{margin:10px 0 0;color:var(--muted);font-size:12px}.chart-sources{margin-top:8px;color:var(--weak);font-size:11px}.chart-sources ul{margin:5px 0 0;padding-left:18px}
table{width:100%;border-collapse:collapse;font-size:13px}th{background:rgba(241,243,245,.82);font-weight:650;text-align:left}th,td{padding:8px 10px;border-bottom:1px solid var(--border)}td:where(:not(:first-child)){text-align:right;font-variant-numeric:tabular-nums}
@media(max-width:760px){body{font-size:15px}.chart-component{margin-left:-4px;margin-right:-4px;padding:17px 12px;border-radius:14px}.chart-component canvas,.chart-card canvas{height:320px}.chart-header{gap:10px}}
@media print{@page{size:A4;margin:14mm}html,body{background:#fff}.chart-component,.chart-card,table{break-inside:avoid;page-break-inside:avoid}.chart-component{border:1px solid #D9DDE3;border-radius:0;background:#fff;box-shadow:none;backdrop-filter:none;-webkit-backdrop-filter:none}.chart-component:before{display:none}.chart-component canvas,.chart-card canvas{height:320px}.chart-tooltip{display:none!important}a{color:var(--text);text-decoration:none}}
"""


FUNDAMENTAL_VISION_STYLE = (
    """
.report-shell{max-width:1160px;margin:28px auto 56px;padding:48px 56px 80px;min-height:100vh;border:1px solid rgba(255,255,255,.74);border-radius:28px;background:rgba(255,255,255,.86);box-shadow:0 28px 80px rgba(34,52,73,.13),inset 0 1px 0 rgba(255,255,255,.96);backdrop-filter:blur(28px) saturate(130%);-webkit-backdrop-filter:blur(28px) saturate(130%)}
.report-hero{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:end;padding:0 0 24px;border-bottom:1px solid var(--border)}.report-hero h1{margin:0 0 8px;font-size:32px;font-weight:720;line-height:1.22;letter-spacing:-.025em}.report-hero>div>p:last-child{margin:0;color:var(--muted);font-size:13px}.hero-tag{align-self:start;padding:11px 14px;border:1px solid rgba(10,132,255,.14);border-radius:12px;background:rgba(10,132,255,.055);color:var(--muted);font-size:12px;line-height:1.55}.hero-tag span{color:var(--weak);font-size:11px}
.summary-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(250px,1fr);gap:32px;margin:38px 0 30px;padding:22px 24px;border:1px solid rgba(255,255,255,.84);border-radius:18px;background:rgba(248,250,252,.68);box-shadow:0 12px 34px rgba(44,62,82,.055);backdrop-filter:blur(18px)}.summary-grid aside{padding-left:28px;border-left:1px solid var(--border)}.summary-grid h2{margin:0 0 12px;padding-bottom:8px;border-bottom:2px solid var(--primary);font-size:19px;font-weight:700;line-height:1.4}.summary-grid ul{margin:8px 0;padding-left:20px}
.mainline,.section-claim{margin:16px 0 0;padding:14px 18px;border-left:4px solid var(--system-blue);border-radius:0 10px 10px 0;background:rgba(10,132,255,.055);font-size:16px;font-weight:620;line-height:1.75}
.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);margin:0 0 46px;border:1px solid var(--border);border-radius:14px;background:rgba(248,250,252,.58);overflow:hidden}.kpi{min-height:92px;padding:14px 16px;border-right:1px solid var(--border)}.kpi:last-child{border-right:0}.kpi span,.kpi small{display:block;color:var(--muted);font-size:12px}.kpi strong{display:block;margin:5px 0 3px;font-size:20px;font-weight:720;line-height:1.3;overflow-wrap:anywhere}
.thematic-section,.section{margin:54px 0 0}.section-heading{display:grid;grid-template-columns:44px 1fr;gap:12px;align-items:baseline;margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid var(--primary)}.section-heading span{color:var(--system-blue);font-size:12px;font-weight:700;letter-spacing:.06em}.section-heading h2{margin:0;font-size:25px;font-weight:720;line-height:1.35;letter-spacing:-.015em}.thematic-section>p:not(.section-claim){max-width:920px}.thematic-section h3,.section h3{margin:30px 0 10px;font-size:19px;font-weight:700}
.observation,.chart-notes{margin-top:20px;padding:14px 18px;border-left:3px solid var(--system-blue);border-radius:0 10px 10px 0;background:var(--soft);font-size:13px}.observation ul,.chart-notes ul{margin:6px 0 0;padding-left:18px}.chart-card{margin:32px 0 44px}.chart-card:not(.chart-component){padding:20px 22px 18px;border:1px solid var(--border);border-radius:18px}
.metric-table{display:grid;grid-template-columns:repeat(4,1fr);margin:0 0 20px;border:1px solid var(--border);border-radius:14px;background:var(--table);overflow:hidden}.metric-table span{min-height:72px;padding:10px 12px;border-right:1px solid var(--border);color:var(--muted);font-size:12px}.metric-table span:last-child{border-right:0}.metric-table b{display:block;margin-top:4px;color:var(--text);font-size:18px;font-weight:720;text-align:right}
.risk{padding-left:16px;border-left:3px solid var(--negative)}.advice{padding-left:16px;border-left:3px solid var(--system-blue)}.advice p,footer{color:var(--muted)}.evidence{margin:48px 0 0;padding:16px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border);font-size:12px}.evidence summary{cursor:pointer;font-weight:650}.evidence ul{overflow-wrap:anywhere}footer{margin-top:40px;padding-top:18px;border-top:1px solid var(--border);font-size:11px}
@media(max-width:760px){.report-shell{margin:0;padding:28px 18px 48px;border:0;border-radius:0}.report-hero,.summary-grid{display:block}.hero-tag{margin-top:16px}.summary-grid{padding:18px}.summary-grid aside{margin-top:22px;padding:20px 0 0;border-left:0;border-top:1px solid var(--border)}.kpi-grid,.metric-table{grid-template-columns:repeat(2,1fr)}.kpi:nth-child(2n),.metric-table span:nth-child(2n){border-right:0}.section-heading{grid-template-columns:34px 1fr}.section-heading h2{font-size:22px}}
@media print{.report-shell{max-width:none;margin:0;padding:0;border:0;border-radius:0;background:#fff;box-shadow:none;backdrop-filter:none;-webkit-backdrop-filter:none}.hero-tag,.chart-sources summary{display:none}.thematic-section,.section,.metric-table,.observation{break-inside:avoid;page-break-inside:avoid}.section-heading,h2,h3{break-after:avoid;page-break-after:avoid}.evidence{font-size:10px}}
"""
    + _TOKENS
).strip()


TECHNICAL_VISION_STYLE = (
    """
.technical-report-shell{max-width:1160px;margin:28px auto 56px;padding:48px 56px 80px;min-height:100vh;border:1px solid rgba(255,255,255,.74);border-radius:28px;background:rgba(255,255,255,.86);box-shadow:0 28px 80px rgba(34,52,73,.13),inset 0 1px 0 rgba(255,255,255,.96);backdrop-filter:blur(28px) saturate(130%);-webkit-backdrop-filter:blur(28px) saturate(130%)}
.technical-hero{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:end;padding:0 0 24px;border-bottom:1px solid var(--border)}.technical-hero h1{margin:0 0 8px;font-size:32px;font-weight:720;line-height:1.22;letter-spacing:-.025em}.technical-hero>div>p:last-child{margin:0;color:var(--muted);font-size:13px}.technical-hero aside{align-self:start;padding:11px 14px;border:1px solid rgba(10,132,255,.14);border-radius:12px;background:rgba(10,132,255,.055);color:var(--muted);font-size:12px;line-height:1.55}.technical-hero aside span{color:var(--weak);font-size:11px}
.technical-copy>h1{display:none}.technical-copy h2{margin:54px 0 20px;padding-bottom:10px;border-bottom:2px solid var(--primary);font-size:25px;font-weight:720;line-height:1.35;letter-spacing:-.015em}.technical-copy h3{margin:30px 0 10px;font-size:19px;font-weight:700}.technical-copy h4{font-size:16px;font-weight:650}.technical-copy li{line-height:1.75}.technical-copy code{padding:1px 4px;border-radius:4px;background:var(--soft)}
.pattern-visuals{margin:22px 0 4px}.pattern-visual{margin:28px 0 42px;padding-top:4px}.pattern-heading{display:flex;align-items:baseline;gap:12px}.pattern-heading span{color:var(--system-blue);font-size:11px;font-weight:700;letter-spacing:.08em}.pattern-heading h3{margin:0;font-size:19px}.pattern-notice,.visual-empty{padding:13px 16px;border-left:3px solid var(--system-blue);border-radius:0 9px 9px 0;background:var(--soft);color:var(--muted);font-size:13px}
.technical-copy .chart-component-overview{margin:22px 0 34px}.technical-copy .chart-component-overview canvas,.technical-copy .pattern-visual .chart-component canvas{height:520px}.technical-copy .chart-component .chart-legend [data-series-id^="support"] i,.technical-copy .chart-component .chart-legend [data-series-id^="resistance"] i,.technical-copy .chart-component .chart-legend [data-series-id^="rsi"] i{height:2px;background-image:linear-gradient(90deg,currentColor 55%,transparent 0);background-size:5px 2px}.technical-copy .chart-component .chart-legend [data-series-id="volume"] i{height:8px;border-radius:1px}
.technical-market-image-card{margin:24px 0 38px;padding:20px 22px 18px;border:1px solid var(--border);border-radius:12px;background:#fff;box-shadow:0 12px 30px rgba(37,55,76,.07)}.technical-market-image-card .chart-header{margin-bottom:14px}.technical-market-image{display:block;width:100%;height:auto;border:1px solid #D3D8E0;background:#fff}.technical-market-image-card .chart-source{margin:10px 0 0}
.signal-rules{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin-top:14px;border:1px solid var(--border);border-radius:11px;background:var(--border);overflow:hidden}.signal-rules>div{padding:10px 12px;background:rgba(255,255,255,.8)}.signal-rules strong,.signal-rules span{display:block}.signal-rules strong{color:var(--system-blue);font-size:11px;letter-spacing:.05em}.signal-rules span{margin-top:2px;color:var(--muted);font-size:12px;line-height:1.55}.chart-source{font-size:11px}
@media(max-width:760px){.technical-report-shell{margin:0;padding:28px 18px 48px;border:0;border-radius:0}.technical-hero{display:block}.technical-hero aside{margin-top:16px}.signal-rules{grid-template-columns:1fr}.technical-copy h2{font-size:22px}.technical-market-image-card{margin-left:-4px;margin-right:-4px;padding:14px 12px;border-radius:8px}.technical-copy .chart-component-overview canvas,.technical-copy .pattern-visual .chart-component canvas{height:430px}}
@media print{.technical-report-shell{max-width:none;margin:0;padding:0;border:0;border-radius:0;background:#fff;box-shadow:none;backdrop-filter:none;-webkit-backdrop-filter:none}.technical-hero aside{display:none}.pattern-visual,.visual-empty,.technical-market-image-card,.technical-copy table{break-inside:avoid;page-break-inside:avoid}.technical-copy h2,.technical-copy h3{break-after:avoid;page-break-after:avoid}.technical-market-image-card{box-shadow:none}.technical-copy .chart-component-overview canvas,.technical-copy .pattern-visual .chart-component canvas{height:430px}}
"""
    + _TOKENS
).strip()
